version: '3'
services:
  nginx: 
    image: openresty/openresty:latest
    container_name: nginx-reverse-proxy
    volumes:
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
    ports:
      - 8080:80

  server_1:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: server_1
    environment:
      - WHO=server_1

  server_2:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: server_2
    environment:
      - WHO=server_2

  ws_server:
    image: jmalloc/echo-server:latest
    container_name: ws_server