version: '3'
services:
  nginx: 
    image: openresty/openresty:latest
    container_name: nginx-reverse-proxy
    volumes:
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./logs:/var/log/nginx/
    ports:
      - 8080:80

  server_1:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: server_1
    ports:
      - 3000:8080
    environment:
      - WHO=server_1

  server_2:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: server_2
    ports:
      - 3001:8080
    environment:
      - WHO=server_2